### ISSUE TITLE
Add test data generator 

### ISSUE THREAD

**Issue by cs-util** [cs-util-com/cscore#10]
The easiest way to find performance problems is to test with realistic data or even better testing with data models that are much larger than whatever will be used in production.

The idea for this ticket is to simplify the generation of mock data for example by providing an interface to enforce very large test models and to help with generation of example values

This ticket is an ideal candidate to be build test driven and potentially improve the performance guards (e.g. add a few more performance focused assertions)

**Comment by sam1rm-hiretech** [comment]
Just spent a good amount of time tinkering with [Bogus](https://github.com/bchavez/Bogus) - were you hoping for this + bare bones?

**Comment by cs-util** [comment]
Hi @sam1rm-hiretech , yes I think using bogus or something similar might be the better option instead of building a full mock data system, and I don't see any generic concepts for small helper classes that get 90% of the default use cases done that could be added to cscore 

So if you want to come up with some ideas here feel free to to do so, I currently think the issue should be rejected and bogus or similar should be used by anyone needing to work with mock data 

I will take the time and add a few other enhancement suggestions in the issue section in case you just want to work on some open source project ;)
