### ISSUE TITLE
Cannot build - Error	CS0246	The type or namespace name 'CSCore' could not be found

### ISSUE THREAD

**Issue by marc-trudel** [cs-util-com/cscore#126]
Hi 
I downloaded the Zip
Started VS 2022
Got a bunch of framework error that the wizard could not fix. 
I responded several time to use .NET 8.1 but at the end none of the project were set with that Framework. This is not a new issue for your repository. I always had this problem since I upgraded to VS2022. Seems unfixable.

Anyway I manuelly set the 3 main project to .NET 8.1. The one in Samples are still with not framework
References are no longer yellow  for the 3  main project.
When I build I receive hundred of error saying CSCore could not be found
Installed : install-package CSCore
Still have the error.

I am hoping to write an app that will detect what app is emitting a sound and log it somewhere ... in the WIndows notification zone hopefully.

I use aboudt 5 Chrome profile each connected to a different Microsoft Tenant as I am a consultant with many customers.
I use different Chrome profile so each one stays connected to a specific MS Tenant for Teams specifically. This way I dont have to logout/login to each Tenant all the time.

WHen someone contacts me, the sound may come from 
Any of these 5 Chrome profile
From local Teams app
From local Outlook app
From Outlook in one of the Chrome tab

Obviously I always miss the call.

I hope that with your library CSCore I will be able to detect.

- The app that just use the sound system
- If it is Chrome, what instance (profile) and in which tab

**Comment by cs-util** [comment]
Hi @marc-trudel , I think you got the wrong library here, you are probably looking for https://github.com/filoe/cscore
