### ISSUE TITLE
Can't import CSCore namespace

### ISSUE THREAD

**Issue by Leonetienne** [cs-util-com/cscore#18]
using CSCore doesn't work. 

Assets\test.cs(4,7): error CS0246: The type or namespace name 'CSCore' could not be found (are you missing a using directive or an assembly reference?)

I imported the plugin via the asset store.
This is a fresh and clean project version 2019.1.10f1.
I am using Visual Studio 2019

**Comment by cs-util** [comment]
Hey @Leonetienne 
I just tested with the same Unity version in a fresh empty project and did not have any problems

From the error it sounds like you have created a file test.cs and are trying to import there the namespace "CSCore" which does not exist, the correct import would in your classes would be:
`using com.csutil;`

I will add a section about the namespaces in the "Getting started" section

**Comment by Leonetienne** [comment]
Thank you for the quick response.
The com.csutil namespace is indeed present.
Finally haha

________________________________
Von: CsUtil.com <notifications@github.com>
Gesendet: Freitag, 19. Juli 2019 06:16
An: cs-util-com/cscore <cscore@noreply.github.com>
Cc: Leonetienne <Leonetienne@hotmail.de>; Mention <mention@noreply.github.com>
Betreff: Re: [cs-util-com/cscore] Can't import CSCore namespace (#18)


Hey @Leonetienne<https://github.com/Leonetienne>
I just tested with the same Unity version in a fresh empty project and did not have any problems

From the error it sounds like you have created a file test.cs and are trying to import there the namespace "CSCore" which does not exist, the correct import would in your classes would be:
using com.csutil;

I will add a section about the namespaces in the "Getting started" section

**Comment by cs-util** [comment]
Ok great, let me know once you tried a few features what you think 👍
