### ISSUE TITLE
Link to AssertV2 examples broken

### ISSUE THREAD

**Issue by hassy-roz** [cs-util-com/cscore#25]
your page says to click here but 404 error (page not found)

**Comment by cs-util** [comment]
hm when I click on the AssertV2 link in the readme.md it scrolls down to https://github.com/cs-util-com/cscore#assertv2 correctly for me. can you paste the link here that does not work for you @hassy-roz ?

**Comment by hassy-roz** [comment]
In ReadMe AssertV2 part, here mention "See here for more examples" which includes link, and the link to "https://github.com/cs-util-com/cscore/blob/master/CsCore/xUnitTests/src/com/csutil/tests/LogTests.cs#L35".
Try to move there but 404 error on my circumstance OMG.

**Comment by cs-util** [comment]
ok I updated the link in the readme, the correct url is now https://github.com/cs-util-com/cscore/blob/master/CsCore/xUnitTests/src/Plugins/CsCoreXUnitTests/com/csutil/tests/LogTests.cs#L63

thanks for reporting this
