### ISSUE TITLE
Some objects were not cleaned up when closing the scene (on scene start)

### ISSUE THREAD

**Issue by spvn** [cs-util-com/cscore#51]
I'm getting the following error every time I start a scene (including the included demo scenes) with cscore imported:

```
Some objects were not cleaned up when closing the scene. (Did you spawn new GameObjects from OnDestroy?)
The following scene GameObjects were found:
Singletons
com.csutil.MainThread

```

Any ideas why? Interestingly I'm getting this when STARTING the scene, not stopping it.

**Comment by cs-util** [comment]
@spvn yes I noticed this warning too a while back and changed a few things about the initialization of the MainThread Singleton that happens in the UnitySetup.cs 

On the latest master branch this warning should not happen anymore, can you try this by copying the latest code from this repo into your project (I did not update the Unity Store yet)?
