### ISSUE TITLE
[REQUEST] Singleton ScriptableObject

### ISSUE THREAD

**Issue by GilbertoBitt** [cs-util-com/cscore#9]
how about a way to create a Singleton ScriptableObject and then use it in-game and make a way to never enable user to create more than one of the type (to guarantee errors free). thank's !

**Comment by cs-util** [comment]
Hey @GilbertoBitt that's an interesting idea.
Unity already kind of handles instances of scriptable objects as singletons, so if you load a scriptable object instance multiple times via `Resources.Load` you will always get the same object but you still can accidentally load different instances of the same scriptable object at once, so for that, I added a test/example how to use the injection logic to ensure you always get the same instance for a ScriptableObject class X, see the example here: 

```
// Load a ScriptableObject instance and set it as the singleton:
var path = "MyExampleScriptableObject_Instance1.asset";
MyExampleScriptableObject x1 = ResourcesV2.LoadScriptableObjectInstance<MyExampleScriptableObject>(path);
IoC.inject.SetSingleton(x1);

// Now that the singleton is set this instance is always returned for the ScriptableObject class:
MyExampleScriptableObject x2 = IoC.inject.Get<MyExampleScriptableObject>(this);
Assert.AreSame(x1, x2);
```

(see here https://github.com/cs-util-com/cscore#scriptable-object-injection--singletons )
