### ISSUE TITLE
Broken prefabs

### ISSUE THREAD

**Issue by equidevium** [cs-util-com/cscore#94]
![image](https://user-images.githubusercontent.com/11783663/221328751-a6917343-45bc-4f8b-bfa5-4ee59bf43fad.png)

After I updated to the latest version 1.8.7 I noticed that the components for unity cannot be added. Somehow I saw that on the resources folder of the UiTemplates all of the prefabs have missing scripts. 

Is this an issue being created due to the update or something else may have broken them?

**Comment by cs-util** [comment]
I quickly tried this with a clean project in Unity 2022.2.1 and for me it still worked fine as usual:
![image](https://user-images.githubusercontent.com/45512166/221338921-adb2390b-d11d-4bdb-8d0d-d4c2be796c84.png)

Which Unity version are you on? To me looks like something happened to the .meta files, eg that they were all regenerated and thats why the prefabs cant find anything. You are probably using the package manager to include cscore right? Maybe try removing this cache of cscore from your pc and packages and then readd it if this helps:
![image](https://user-images.githubusercontent.com/45512166/221338990-3294e468-519d-4472-9ae0-387b76a3f3fe.png)

**Comment by equidevium** [comment]
I rechecked it as you said and it still was havint the same problem. Unity version 2022.2.5f1

What fixed it was to reimport the entire assets. Which I found a little weird. You are right though there must be something that Unity may have changed with their metafiles manipulation and I also noticed that at some point they were regenerated. 

Not sure why though.
