### ISSUE TITLE
Unity LTS Support broken - 2021.3.23f1 

### ISSUE THREAD

**Issue by Dak0r** [cs-util-com/cscore#98]
We wanted to update our project from 1.8.5 to the latest release 1.8.8 and found it breaks compatibility with the lastet available Unity LTS release (2021.3.23f1), as it doesn't have the [useDelaunayMesh](https://docs.unity3d.com/2023.2/Documentation/ScriptReference/PolygonCollider2D-useDelaunayMesh.html) option, see https://docs.unity3d.com/2021.3/Documentation/ScriptReference/PolygonCollider2D.html

So the `PolygonCreatorV2`, which was added in 1.8.6, causes a compiler error

I'm not sure if this is intentional? (I couldn't find a list of supported unity releases)

It would b easy to fix by checking the `UNITY_2022_1_OR_NEWER` symbol

**Comment by cs-util** [comment]
Fixed in new bugfix release, please update here in case there are still problems
